//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_taller
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulos
    {
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> precio { get; set; }
    }
}
